### ISSUE TITLE
qqreadnode固定ck，阅读时长不增加

### ISSUE THREAD

**Issue by RockZhou8** [ziye12/JavaScript#47]
js已经更新到2021年1月3日15:50的commit了https://github.com/ziye12/JavaScript/commit/dcab147e10b059d61e193c9d569383c6af5cd93b

`const BOX = 2;//设置为0 日常任务，设置为1 单开宝箱，设置为2 完整功能版`
`const NODE = 1;//如需固定ck，请设置为1，下载到本地使用`

企鹅读书14🔔

========== 【970702】 ==========
【数据更新】:更新ok
【时长查询】:今日阅读208分钟
【本周阅读时长】:619分钟
【现金余额】:1.81元
【第1期】:时间1.1-3
 已邀请0人，再邀请1人获得2000金币
【明日打卡】:288金币,去查看
【立即阅读《轮回乐园》】:100金币,已完成
【阅读任务】:600金币,已完成
【看视频领金币】:500金币,已完成
【宝箱任务24】:396.439秒后领取
【粉丝金币分成】:0个好友,0金币

过了一段时间之后的：
企鹅读书14🔔

========== 【970702】 ==========
【数据更新】:更新ok
【时长查询】:今日阅读208分钟
【本周阅读时长】:619分钟
【现金余额】:1.85元
【第1期】:时间1.1-3
 已邀请0人，再邀请1人获得2000金币
【明日打卡】:288金币,去查看
【立即阅读《轮回乐园》】:100金币,已完成
【阅读任务】:600金币,已完成
【看视频领金币】:500金币,已完成
【宝箱任务27】:0秒后领取
【粉丝金币分成】:0个好友,0金币
【宝箱奖励27】:获得79金币
【宝箱翻倍】:获得79金币

**Comment by Arrogance-H** [comment]
云函数上也出现不加时长的

**Comment by RockZhou8** [comment]
> 云函数上也出现不加时长的

那208分钟是我用loon跑qqreads.js的，那个可以。
我想弄到本地，结果发现不增加阅读时长

**Comment by RockZhou8** [comment]
loon上用qqreadck.js重新导出三大件，又tm行了，666
